services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    environment:
      - DATABASE_URL=postgres://postgres:postgres@localhost
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  chromedriver:
    image: robcherry/docker-chromedriver:latest
    restart: unless-stopped
    network_mode: service:db

volumes:
  postgres-data:
